var DATA = [
      { id:0, label:"delete-by-id", link:"mule/solr.html#delete-by-id", type:"method" },
      { id:1, label:"delete-by-query", link:"mule/solr.html#delete-by-query", type:"method" },
      { id:2, label:"index", link:"mule/solr.html#index", type:"method" },
      { id:3, label:"index-pojo", link:"mule/solr.html#index-pojo", type:"method" },
      { id:4, label:"message-to-input-document-transformer", link:"mule/solr.html#message-to-input-document-transformer", type:"method" },
      { id:5, label:"org.apache.solr.client.solrj.transformers", link:"java/org/apache/solr/client/solrj/transformers/package-summary.html", type:"package" },
      { id:6, label:"org.apache.solr.client.solrj.transformers.ORDEREnumTransformer", link:"java/org/apache/solr/client/solrj/transformers/ORDEREnumTransformer.html", type:"class" },
      { id:7, label:"org.mule.modules", link:"java/org/mule/modules/package-summary.html", type:"package" },
      { id:8, label:"org.mule.modules.SolrConnector", link:"java/org/mule/modules/SolrConnector.html", type:"class" },
      { id:9, label:"org.mule.modules.SolrModuleException", link:"java/org/mule/modules/SolrModuleException.html", type:"class" },
      { id:10, label:"org.mule.modules.adapters", link:"java/org/mule/modules/adapters/package-summary.html", type:"package" },
      { id:11, label:"org.mule.modules.adapters.SolrConnectorCapabilitiesAdapter", link:"java/org/mule/modules/adapters/SolrConnectorCapabilitiesAdapter.html", type:"class" },
      { id:12, label:"org.mule.modules.adapters.SolrConnectorConnectionManager", link:"java/org/mule/modules/adapters/SolrConnectorConnectionManager.html", type:"class" },
      { id:13, label:"org.mule.modules.adapters.SolrConnectorConnectionManager.ConnectionKey", link:"java/org/mule/modules/adapters/SolrConnectorConnectionManager.ConnectionKey.html", type:"class" },
      { id:14, label:"org.mule.modules.adapters.SolrConnectorLifecycleAdapter", link:"java/org/mule/modules/adapters/SolrConnectorLifecycleAdapter.html", type:"class" },
      { id:15, label:"org.mule.modules.config", link:"java/org/mule/modules/config/package-summary.html", type:"package" },
      { id:16, label:"org.mule.modules.config.DeleteByIdDefinitionParser", link:"java/org/mule/modules/config/DeleteByIdDefinitionParser.html", type:"class" },
      { id:17, label:"org.mule.modules.config.DeleteByQueryDefinitionParser", link:"java/org/mule/modules/config/DeleteByQueryDefinitionParser.html", type:"class" },
      { id:18, label:"org.mule.modules.config.IndexDefinitionParser", link:"java/org/mule/modules/config/IndexDefinitionParser.html", type:"class" },
      { id:19, label:"org.mule.modules.config.IndexPojoDefinitionParser", link:"java/org/mule/modules/config/IndexPojoDefinitionParser.html", type:"class" },
      { id:20, label:"org.mule.modules.config.QueryDefinitionParser", link:"java/org/mule/modules/config/QueryDefinitionParser.html", type:"class" },
      { id:21, label:"org.mule.modules.config.SolrConnectorConfigDefinitionParser", link:"java/org/mule/modules/config/SolrConnectorConfigDefinitionParser.html", type:"class" },
      { id:22, label:"org.mule.modules.config.SolrConnectorNamespaceHandler", link:"java/org/mule/modules/config/SolrConnectorNamespaceHandler.html", type:"class" },
      { id:23, label:"org.mule.modules.processors", link:"java/org/mule/modules/processors/package-summary.html", type:"package" },
      { id:24, label:"org.mule.modules.processors.DeleteByIdMessageProcessor", link:"java/org/mule/modules/processors/DeleteByIdMessageProcessor.html", type:"class" },
      { id:25, label:"org.mule.modules.processors.DeleteByQueryMessageProcessor", link:"java/org/mule/modules/processors/DeleteByQueryMessageProcessor.html", type:"class" },
      { id:26, label:"org.mule.modules.processors.IndexMessageProcessor", link:"java/org/mule/modules/processors/IndexMessageProcessor.html", type:"class" },
      { id:27, label:"org.mule.modules.processors.IndexPojoMessageProcessor", link:"java/org/mule/modules/processors/IndexPojoMessageProcessor.html", type:"class" },
      { id:28, label:"org.mule.modules.processors.QueryMessageProcessor", link:"java/org/mule/modules/processors/QueryMessageProcessor.html", type:"class" },
      { id:29, label:"org.mule.modules.transformers", link:"java/org/mule/modules/transformers/package-summary.html", type:"package" },
      { id:30, label:"org.mule.modules.transformers.MessageToInputDocumentTransformerTransformer", link:"java/org/mule/modules/transformers/MessageToInputDocumentTransformerTransformer.html", type:"class" },
      { id:31, label:"query", link:"mule/solr.html#query", type:"method" }

    ];
