/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules;

import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.client.solrj.SolrServer;
import org.apache.solr.client.solrj.SolrServerException;
import org.apache.solr.client.solrj.impl.CommonsHttpSolrServer;
import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.client.solrj.response.SolrPingResponse;
import org.mule.api.ConnectionExceptionCode;
import org.mule.api.annotations.*;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.MalformedURLException;


/**
 * Module for Apache Solr Integration, it is based on the SolrJ Java Client API and allows interaction
 * with Apache Solr standalone servers.
 *
 * @author Juan Alberto López Cavallotti
 */

@Connector(name = "solr", schemaVersion = "1.0.0-SNAPSHOT", friendlyName = "Solr")
public class SolrConnector
{

    private static final Logger logger = LoggerFactory.getLogger(SolrConnector.class);

    //the SolrServer connection
    private SolrServer server;

    /**
     * The URL of the Solr server to connect to. To define the solr core to use, specify it here, otherwise the default
     * core will be used.
     */
    @Configurable
    @Optional @Default("http://localhost:8983/solr")
    private String serverUrl;

    /**
     * Connect to the Solr Server using commons http client gateway.
     */
    @Connect
    public synchronized void connect() throws ConnectionException {
        try {
            server = new CommonsHttpSolrServer(serverUrl);
        } catch (MalformedURLException ex) {
            logger.error("The url: " + serverUrl +" is malformed.");
            throw new ConnectionException(ConnectionExceptionCode.UNKNOWN, ex.getMessage(), "Url is not properly written", ex);
        } catch(Exception ex) {
            throw new ConnectionException(ConnectionExceptionCode.UNKNOWN, ex.getMessage(), "Could not connect to solr", ex);
        }
    }

    /**
     * Identify the connection.
     * @return null, not used at this time.
     */
    @ConnectionIdentifier
    public String connectionIdentifier() {
        return null;
    }

    /**
     * Disconnect from the server, nothing special needed at this time.
     */
    @Disconnect
    public synchronized void disconnect() {
        if (server == null) {
            return;
        }
        //do something to disconnect.
        server = null;
    }

    /**
     * Validate the connection by sending a ping request.
     * @return true if the ping call succeeds, false otherwise.
     */
    @ValidateConnection
    public boolean isConnected() {
        if (server == null) {
            return false;
        }

        try {
            SolrPingResponse response = server.ping();

            if (logger.isDebugEnabled()) {
                logger.debug("Pinged the server, response time is: " + response.getQTime());
            }

            if (response.getQTime() > 0) {
                return true;
            }

        } catch (Exception ex) {
            logger.error("Got exception while trying to Ping Server", ex);
            return false;
        }
        //default answer
        return false;
    }

    /**
     * Submit a query to the server and get the results.
     *
     * {@sample.xml ../../../doc/solr-connector.xml.sample solr:query}
     *
     * @param q this is the query string called 'q' using solr's nomenclature, normally this has the form of
     *          <em>field</em>:<em>value</em> or just <em>value</em> for querying the default field. Please take a look
     *          at solr's documentation for info on how to write queries.
     * @param handler which handler to use when querying.
     * @return a {@link QueryResponse QueryResponse} object with the search results.
     * @throws SolrServerException when querying the server fails.
     */
    @Processor
    public QueryResponse query(String q, @Optional @Default("/select") String handler) throws SolrServerException {

        SolrQuery query = new SolrQuery(q);
        query.setQueryType(handler);

        return server.query(query);
    }

    public String getServerUrl() {
        return serverUrl;
    }

    public void setServerUrl(String serverUrl) {
        this.serverUrl = serverUrl;
    }
}
